Demonstrator/ResearchInterface/genecoop/urls.py
from django.urls import path

from . import views

app_name = 'genecoop'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/consent', views.ConsentView.as_view(), name='consent'),
    path('<int:pk>/sign', views.SignConsentView.as_view(), name='sign'),
    # path('<int:key>/operation/', views.OperationsView.as_view(), name='operation'),
    path('genconsent/', views.genconsent, name='genconsent'),
    path('signconsent/', views.signconsent, name='signconsent'),
]

Demonstrator/ResearchInterface/genecoop/templates/genecoop/landing.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Researcher Space</title>
    <link rel="stylesheet" type="text/css" href="{% static 'researcher_req/login.css' %}">
</head>

<body>


{% if request.user.is_authenticated %}

    {% include "header.html" %}

{% else %}

<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
        <h2 class="active"> Sign In </h2>

        <!-- Icon -->
        <div class="fadeIn first">
            <img src="{% static 'researcher_req/images/logo_64.png' %}" id="icon" alt="GeneCoop" />
        </div>
        
        <!-- Login Form -->
        <form action="{% url 'researcher_req:check_login' %}" method="post">
            {% csrf_token %}
            <input type="hidden" id="challenge" name="challenge" value={{ challenge }}>
            <input type="text" id="username" class="fadeIn second" name="username" placeholder="username">
            <input type="hidden" id="response" class="fadeIn third" name="response" placeholder="response">
            <input type="submit" class="fadeIn fourth" value="Log In">
        </form>
    </div>
</div>

{% endif %}

Demonstrator/ResearchInterface/genecoop/templates/genecoop/signconsent.html
{% load static %}
{% load genecoop_extras %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>GeneCoop Request for Consent</title>
        <link rel="stylesheet" type="text/css" href="{% static 'genecoop/user.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
        <main class="consent_page">
            <div><a href="{% url 'genecoop:index' %}">Home</a></div>
            <h1 class="consent_request_label">GeneCoop Request for Consent</h1>
            <form class="consent_request" action="{% url 'genecoop:signconsent' %}" method="post">
                <header class="consent_request_header">
                    <h2 class="consent_request_title">{{ my_request.description }}</h2>
                    <p class="consent_request_description"><i class="organisation">{{ my_request.researcher.user }}&nbsp;<sup><i class="fa fa-briefcase"></i></sup></i> asks for your consent to the following permissions:
                    </p>
                </header>
                {% csrf_token %}
                {% for operation in my_set.operations %}
                <section class="consent_request_item">
                    <h3 class="consent_request_item_title">{{ operation.text}}</h3>
                    <h4 class="consent_request_section_title">Purpose</h4>
                    <p class="consent_request_section_text">{{ operation.description|org|pd|tech|safe}}</p>
                    <h4 class="consent_request_section_title">What does it mean for my personal data?</h4>
                    <ul>
                        {% for statement in operation.statements %}
                        <li>{{ statement|org|pd|tech|safe}}</li>
                        {% endfor %}
                    </ul>
                    <br/>
                    <strong>
                        <div data-label="Options" {%if operation.required %} class="mandatory" {% endif %}>
                            I agree to this:&nbsp;
                            {% for option in operation.options %}
                            <label for="{{ operation.key }}">{{ option.text }}</label>
                            <input type="radio" name="option-{{ operation.key }}" id="{{ operation.key }}" value="{{ option.key }}" onchange="return onAgreementChange(event);">
                            {% endfor %}
                        </div>
                    </strong>
                    <br/>
                    ({% if operation.required == True  %}Required{% else %}Optional{% endif %})

                </section>
                {% endfor %}
                <section>
                    <h2>Summary of permissions</h2>
                    <p>As part of {{ my_request.description }} conducted by {{ my_request.researcher.user }} I agree to the following:
                    <ul id="permissions">
                    {% for operation in my_set.operations %}
                        {% for permission in operation.permissions %}
                        <li style="display:none" class="op_{{operation.key}}">{{ permission|org|pd|tech|safe }}</li>
                        {% endfor %}
                    {% endfor %}
                    </ul>
                </section>

                <footer class="consent_sign_footer">
                    <input type="hidden" id="consentID" name="consentID" value={{my_set.token}}>
                    <input id="submitButton" type="submit" data-label="Submit" class="button" value="Sign agreement" disabled />
                </footer>
            </form>
        </main>
        <script type="text/javascript" src="{% static 'genecoop/user.js' %}"></script>
    </body>

</html>