Demonstrator/ResearchInterface/genecoop/urls.py
from django.urls import path

from . import views

app_name = 'genecoop'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/consent', views.ConsentView.as_view(), name='consent'),
    path('<int:pk>/sign', views.SignConsentView.as_view(), name='sign'),
    # path('<int:key>/operation/', views.OperationsView.as_view(), name='operation'),
    path('genconsent/', views.genconsent, name='genconsent'),
    path('signconsent/', views.signconsent, name='signconsent'),
]

Demonstrator/ResearchInterface/researcher_app/urls.py
from django.urls import path, re_path

from . import views

app_name = 'researcher_app'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('complete/',views.complete_view, name='complete'),
    path('login/', views.login_view, name='login'),
    path('check_login/', views.check_login, name='check_login'),

    path('logout/', views.logout_view, name='logout'),
    
    path('profile/', views.profile_view, name='profile'),
    path('fill_profile/', views.fill_profile, name='fill_profile'),
    
    
    path('prepare_request/', views.prepare_request_view, name='prepare_request'),
    path('sign_request/', views.sign_request, name='sign_request'),
    path('store_request/', views.store_request, name='store_request'),
    
    
    path('<int:pk>/', views.request_view, name='request'),
    
    path('perform_action/', views.perform_action, name='perform_action'),

    path('<str:key>/experiment/', views.experiment_view, name='experiment'),    

    path('download_request/<int:id>', views.download_request, name='download_request'),
]

Demonstrator/ResearchInterface/researcher_app/models.py
from datetime import datetime
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db import models

from consent_server.constants import TITLE_LENGTH, DESCR_LENGTH, EXPERIMENTS_LENGTH, TOKEN_LENGTH, PUBLICKEY_LENGTH, SIGNATURE_LENGTH
from id_app.models import User

class Researcher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=DESCR_LENGTH)
    institute = models.CharField(max_length=TITLE_LENGTH)
    institute_publickey = models.CharField(max_length=PUBLICKEY_LENGTH)

    def __str__(self):
        return self.user.username


class Request(models.Model):
    researcher = models.ForeignKey(Researcher, on_delete=models.CASCADE)
    name = models.CharField(max_length=TITLE_LENGTH)
    description = models.CharField(max_length=DESCR_LENGTH)
    experiments = models.CharField(max_length=EXPERIMENTS_LENGTH, default="")
    token = models.CharField(max_length=TOKEN_LENGTH, unique=True)
    token_time = models.FloatField(default=0)
    token_signature = models.CharField(max_length=SIGNATURE_LENGTH, default="")
    request_created = models.DateTimeField(
        'create date', default=timezone.make_aware(datetime(1900, 1, 1)))
    request_checked = models.DateTimeField(
        'checked date', default=timezone.make_aware(datetime(1900, 1, 1)))

    class RequestStatus(models.TextChoices):
        NOTSENT = 'NOT SENT', _('Request has not been sent')
        NOTREPLIED = 'NOT REPLIED', _('Request has not been replied')
        REPLIED = 'REPLIED', _('Request has been replied')

    status = models.CharField(
        max_length=15,
        choices=RequestStatus.choices,
        default=RequestStatus.NOTSENT,
    )

    def created(self):
        self.request_created = timezone.now()
        self.status = self.RequestStatus.NOTREPLIED

    def replied(self):
        self.request_checked = timezone.now()
        self.status = self.RequestStatus.REPLIED

    def not_replied(self):
        self.request_checked = timezone.now()
        self.status = self.RequestStatus.NOTREPLIED

    def is_replied(self):
        return self.status == self.RequestStatus.REPLIED

    def __str__(self):
        return self.description

Demonstrator/ResearchInterface/researcher_app/views.py
import requests
import logging
import inspect
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required


from .models import Request, Researcher

import consent_server.utils as labut
from consent_server.constants import ISSIGNED_URL, ALLOWEDEXP_URL, LOGEXP_URL

# Get an instance of a logger
logger = logging.getLogger(__name__)
# print(f'Logger {__name__}')

myConfig = labut.read_conf('researcher')
mySerializedExperiments = labut.SerializeExperiments(myConfig)


def _update_request(request_obj):
    """
        Checks whether a request has been signed
        and what experiments are allowed
    """
    if request_obj.token == None or request_obj.token == "":
        logger.debug(f'Request {request_obj.id} does not have a token yet')
        return

    # Perform API call
    logger.debug(f'Perform request {ISSIGNED_URL}/{request_obj.token}')
    cons_req = requests.get(f'{ISSIGNED_URL}/{request_obj.token}')

    # print(cons_req.json()['signed'])
    request_obj.not_replied()

    if cons_req.status_code == 200:
        if 'signed' in cons_req.json() and cons_req.json()['signed']:
            # request has been signed
            logger.debug(f'Request result: {cons_req.json()}')
            request_obj.replied()

            # Check what experiments are allowed with an API call
            logger.debug(
                f'Perform request {ALLOWEDEXP_URL}/{request_obj.token}')
            exp_req = requests.get(f'{ALLOWEDEXP_URL}/{request_obj.token}')

            if exp_req.status_code == 200:
                logger.debug(f'Request result: {exp_req.json()}')
                exp_results = exp_req.json()
                # print(f'op_result: {exp_results}')

                # Read and deserialise experiments contained in the request
                logger.debug(f'Start deserialize experiments')

                mySerializedExperiments.unserialize(request_obj.experiments)
                logger.debug(
                    f'Deserialize experiments: {request_obj.experiments}')

                for op_result in exp_results:
                    # print(f"id: {op_result['id']}")
                    mySerializedExperiments.select_option_id(
                        op_result['id'], op_result['chosen_option'])

                request_obj.experiments = mySerializedExperiments.serialize()
                logger.debug(f'Serialize experiments: {request_obj.experiments}')
            else:
                logger.error(
                    f'Call {ALLOWEDEXP_URL}/{request_obj.token} gave {exp_req.status_code} with {exp_req.text}')
    else:
        logger.error(
            f'Call {ISSIGNED_URL}/{request_obj.token} gave {cons_req.status_code} with {json.dumps(cons_req.text)}')

    request_obj.save()


def _gen_desc_op(id):
    experiment_view = {}
    experiment_view['id'] = id
    experiment_view['name'] = myConfig.get_experiment_obj(id).name
    experiment_view['description'] = myConfig.get_experiment_obj(id).description
    return experiment_view


def _gen_experiments(experiments):
    # mySerializedExperiments.reset()
    mySerializedExperiments.unserialize(experiments)
    experiments_view = []
    for experiment in mySerializedExperiments.experiments:
        experiment_view = _gen_desc_op(experiment['id'])
        experiment_view['chosen_option'] = experiment['chosen_option']
        experiment_view['reply'] = experiment['reply']
        opt_obj = myConfig.get_option_obj(experiment['chosen_option'])
        if not opt_obj == None:
            experiment_view['chosen_option_name'] = opt_obj.name

        experiments_view.append(experiment_view)
    return experiments_view

def _pageset_for(request_set, pk):
    """
    Return the requests, checking wheter they have been signed
    and what experiments are allowed for the given request set
    """
    requests_view = []
    
    for request_obj in request_set:
        _update_request(request_obj)
        logger.debug(f'Request {request_obj.id} updated')
        request_view = {}
        request_view['id'] = request_obj.id
        request_view['token'] = request_obj.token
        request_view['name'] = request_obj.name
        request_view['description'] = request_obj.description
        # request_view['user_id'] = request_obj.user_id
        request_view['status'] = request_obj.status

        experiments_view = _gen_experiments(request_obj.experiments)

        request_view['experiments'] = experiments_view
        logger.debug(f'Experiments added: {json.dumps(experiments_view)}')
        # print(f"view experiments {json.dumps(request_view['experiments'])}")

        requests_view.append(request_view)
        logger.debug(f'Request added: {json.dumps(request_view)}')

    if not pk == None:
        #  Return if just one request is needed
        logger.debug(f'Return request: {json.dumps(requests_view[0])}')
        return requests_view[0]

    experiments_view = []
    for op_id in myConfig.experiments.keys():
        experiment_view = {}
        op_obj = myConfig.get_experiment_obj(op_id)
        experiment_view['id'] = op_obj.id
        experiment_view['name'] = op_obj.name
        experiments_view.append(experiment_view)
        logger.debug(f'Experiment added: {json.dumps(experiment_view)}')

    my_set = {}
    my_set['requests'] = requests_view
    my_set['experiments'] = experiments_view
    logger.debug(f'Return queryset: {json.dumps(my_set)}')
    return my_set


def _gen_pageset(pk):
    """
        generate a pageset for the private key
        if no private key is given all objects are returned
    """
    request_set = None
    if pk == None:
        request_set = Request.objects.all()
    else:
        request_set = [Request.objects.get(pk=pk)]

    return _pageset_for(request_set,pk) 

# class LoginView(LoginView):
#     template_name = 'researcher_app/login.html'


def logout_view(request):
    logger.debug(f'Logout view request')
    template_name = 'researcher_app/logout.html'

    if request.user.is_authenticated:
        logout(request)
        return render(request, template_name)
    return HttpResponseRedirect(reverse('researcher_app:login'))


def login_view(request):
    logger.debug(f'Login view request')
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('researcher_app:index'))
    template_name = 'researcher_app/login.html'
    context = {'challenge': labut.generate_random_challenge()}
    return render(request, template_name, context)


@login_required(login_url='researcher_app:login')
def profile_view(request):
    """
        Store information about the researcher
    """
    logger.debug(f'Profile view request')
    template_name = 'researcher_app/profile.html'
    researcher = Researcher.objects.get(user=request.user)
    researcher_obj = {
        "name": f'{researcher.user.first_name} {researcher.user.last_name}',
        "email": researcher.user.email,
        "institute": researcher.institute
    }
    context = {'researcher': researcher_obj}
    logger.debug(f'Profile view rendering: {json.dumps(context)}')
    return render(request, template_name, context)


@login_required(login_url='researcher_app:login')
def index_view(request):
    logger.debug(f'Index view request')
    template_name = 'researcher_app/index.html'
    request_set = Request.objects.filter(status="NOT REPLIED")
    pageset = _pageset_for(request_set,None)
    context = {'my_set': pageset}
    logger.debug(f'Index view rendering: {json.dumps(context)}')
    return render(request, template_name, context)

@login_required(login_url='researcher_app:login')
def complete_view(request):
    logger.debug(f'Complete view request')
    template_name = 'researcher_app/complete.html'
    request_set = Request.objects.filter(status="REPLIED")
    pageset = _pageset_for(request_set,None)
    context = {'my_set': pageset}
    logger.debug(f'Complete view rendering: {json.dumps(context)}')
    return render(request, template_name, context)

@login_required(login_url='researcher_app:login')
def prepare_request_view(request):
    logger.debug(f'New Request view request')
    template_name = 'researcher_app/prepare_request.html'
    context = {'my_set': _gen_pageset(None)}
    return render(request, template_name, context)


@login_required(login_url='researcher_app:login')
def request_view(request, pk):
    logger.debug(f'Request view request')
    template_name = 'researcher_app/request.html'
    context = {'req': _gen_pageset(pk)}
    logger.debug(f'Request view rendering: {json.dumps(context)}')
    return render(request, template_name, context)

@login_required(login_url='researcher_app:login')
def experiment_view(request, id):
    logger.debug(f'Experiment view request')
    template_name = 'researcher_app/experiment.html'
    exp_obj = myConfig.get_experiment_obj(id)
    opts_view = []
    for exp_id in exp_obj.options:
        opt_view = {}
        opt_obj = myConfig.get_option_obj(exp_id)
        opt_view['id'] = opt_obj.id
        opt_view['name'] = opt_obj.name
        opts_view.append(opt_view)

    exp_view = {}
    exp_view['options'] = opts_view
    exp_view['name'] = exp_obj.name
    exp_view['description'] = exp_obj.description

    context = {'experiment': exp_view}
    logger.debug(f'Experiment view rendering: {json.dumps(context)}')
    return render(request, template_name, context)


def check_login(request):
    """
        Check credentials and log user in
    """
    logger.debug(f'Call to {inspect.currentframe().f_code.co_name}')
    if request.method == 'POST':
        if 'username' in request.POST and 'challenge' in request.POST and 'response' in request.POST:
            username = request.POST['username']

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/complete.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Answered Requests{% endblock %}


{% block content %}

<div class="wrapper">
  <h1>Answered Requests</h1>

  {% if my_set.requests %}
  {% for request in my_set.requests %}
  <a class="pane request" href="{% url 'researcher_app:request' request.id %}">
    <div class="top-right">
      <div class="token">{{ request.token }}</div>
    </div>
    <h2 class="first-child">{{request.name }}</h2>
    <div>{{ request.description }}</div>
    <ul class="consent-options">
      {% for experiment in request.experiments %}
      {% if experiment.chosen_option != -1 %}
      <li class="{% if experiment.chosen_option_name == 'Yes' %}chosen{% endif %}">{{ experiment.name }}</li>
      {% else %}
      <li>{{ experiment.name }}</li>
      {% endif %}
      {% endfor %}
    </ul>
  </a>
  {% endfor %}
  {% else %}
  <div class="pane">No answered requests.</div>
  {% endif %}
</div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/index.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Requests{% endblock %}


{% block content %}

<div class="wrapper">
    <h1>Pending Requests</h1>

    <div class="requests flow">
        {% if my_set.requests %}
        {% for request in my_set.requests %}
            <a class="pane request" href="{% url 'researcher_app:request' request.id %}">
                <div class="top-right">
                  <div class="token">{{ request.token }}</div>
                </div>
                <h2>{{ request.name }}</h2>
                <div>{{ request.description }}</div>
                <ul class="experiments-requested">
                    {% for experiment in request.experiments %}
                        {% if experiment.chosen_option != -1 %}
                        <li>{{ experiment.name }} : {{experiment.chosen_option_name}}</li>
                        {% else %}
                        <li>{{ experiment.name }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </a>
        {% endfor %}
        {% else %}
        <div class="pane">No pending requests.</div>
        {% endif %}
    </div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/login.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>GeneConsent</title>
    <link rel="stylesheet" href="{% sass_src 'css/style.scss' %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static '/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static '/safari-pinned-tab.svg' %}" color="#000000">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
</head>

<body class="page__login researcher">

    {% if request.user.is_authenticated %}

    {% include "header_res.html" %}

    {% else %}

    <div class="wrapper">
        <div id="formContent" class="pane">
            <img id="logo" src="{% static 'images/logo.svg' %}" alt="Logo GeneConsent" />

            <div id="no-genecoop-plugin">
                <p class="instruction">
                    You need GeneCoop add-on to login.<br />
                    Click <a href="/static/researcher_app/genecoop_research.xpi">here</a> to install it.
                </p>
            </div>

            <div id="yes-genecoop-plugin" style="display: none; visibility: hidden;">
                <div id="action-required-genecoop-plugin">
                    <p class="instruction">Please 'Login' from your GeneCoop add-on.<br /></p>
                </div>
                <div id="action-done-genecoop-plugin" style="display: none; visibility: hidden;">
                    <p class="instruction">Click Proceed to continue.<br /></p>
                </div>

                <form class="form-one-line" action="{% url 'researcher_app:check_login' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" id="challenge" name="challenge" value={{ challenge }}>
                    <input type="text" id="username" name="username" placeholder="" size="35" readonly>
                    <input type="hidden" id="response" name="response" placeholder="response">
                    <button id="proceedButton" type="submit" style="visibility:hidden;">Proceed</button>
                </form>

            </div>

        </div>
    </div>

    {% endif %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/logout.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Logout{% endblock %}

{% block content %}

<div class="wrapper">
  <div class="pane">
    {% if request.user.is_authenticated %}
      <p>Strange, you are still logged in {{ request.user }}!</p>
    {% else %}
      <p>You are now logged out</p>
    {% endif %}
  </div>
</div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/operation.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Experiment{% endblock %}


{% block content %}
<h1>{{ experiment.name }}</h1>
<div>Description: {{ experiment.description }}</div>
<div>Possible answers:</div>
<ul>
    {% for option in experiment.options %}
    <li>{{ option.name }}
    </li>
    {% endfor %}
</ul>

</ul>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/prepare_request.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - New Request{% endblock %}


{% block content %}

<div class="wrapper">
  <h1>New Request</h1>

  <form class="pane flow" action="{% url 'researcher_app:sign_request' %}" method="post">
    {% csrf_token %}

    <div class="form-row">
      <label for="name">Title</label>
      <input type="text" name="name" value="" required>
    </div>

    <div class="form-row">
      <label for="description">Description</label>
      <textarea cols="40" rows="5" name="description" value="" required></textarea>
    </div>

    <div class="form-row">
      <label for="experiments">Experiments</label>
      <div class="form-column">
        {% for experiment in my_set.experiments %}
        <div class="checkbox">
          <input type="checkbox" name="experiments" id="experiment{{ forloop.counter }}" value="{{ experiment.id }}">
          <label for="experiment{{ forloop.counter }}">{{ experiment.name }}</label>
        </div>
        {% endfor %}
      </div>
    </div>

    <div class="form-row">
      <label for="nr_users">Users</label>
      <select name="nr_users" id="nr_users">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
    </div>

    <div class="form-buttons">
      <input type="submit" value="Create request">
    </div>
  </form>
</div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/profile.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Profile{% endblock %}


{% block content %}

<div class="wrapper">
    <h1>Profile</h1>

    <form class="pane flow" action="{% url 'researcher_app:fill_profile' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
          <label for="name">Name</label>
          <input type="text" id="name" name="name" value="{{ researcher.name }}">
        </div>

        <div class="form-row">
          <label for="email">Email</label>
          <input type="text" id="email" name="email" value="{{ researcher.email }}">
        </div>

        <div class="form-row">
          <label for="institute">Institute</label>
          <input type="text" id="institute" name="institute" value="{{ researcher.institute }}">
        </div>

        <div class="form-buttons">
          <button type="submit">Update profile</button>
        </div>

    </form>
</div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/request.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Request{% endblock %}


{% block content %}

<div class="wrapper">
  <h1>{{ req.name }}</h1>

  <div class="pane request">
    <div class="top-right">
      <div class="token">{{ req.token }}</div>
      <div class="status">{{ req.status }}</div>
    </div>

    <p>{{ req.description }}</p>

    <h2>Experiments</h2>
    <div class="flow">
      {% for experiment in req.experiments %}
      <section class="experiment">
        <h3>{{experiment.name }}</h3>
        <p>{{ experiment.description }}</p>
        {% if experiment.chosen_option != -1 %}
        <ul class="consent-options">
          <li class="{% if experiment.chosen_option_name == 'Yes' %}chosen{% endif %}">{{experiment.chosen_option_name}}</li>
        </ul>
        {% else %}
        <p>No reply</p>
        {% endif %}
        <p>{{ experiment.reply }}</p>
        <div>
          {% if req.status == "REPLIED" %}
          <form action="{% url 'researcher_app:perform_action' %}" method="post">
            {% csrf_token %}
            <input type="hidden" id="Token" name="Token" value={{req.token}}>
            <input type="hidden" id="experimentId" name="experimentId" value={{experiment.id}}>
            <input type="submit" value="Run Analysis">
          </form>
          {% else %}
          No experiment possible
          {% endif %}
        </div>
      </section>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/sign_request.html
{% extends 'base_res.html' %}

{% block title %}GeneConsent - Request signature{% endblock %}


{% block content %}

<div class="wrapper">
    <h1>Request signature</h1>

    <form class="pane request" action="{% url 'researcher_app:store_request' %}" method="post">
        {% csrf_token %}

        <h2 class="first-child">{{ request.name }}</h2>
        <p>{{ request.description }}</p>

        <h3>Experiments</h3>
        <ul class="experiments-requested">
          {% for experiment in request.experiments %}
          <li>{{ experiment.name }}</li>
          {% endfor %}
        </ul>

        <h3>{% if request.token_data|length > 1 %} Tokens {% else %} Token {% endif %}</h3>
        <ul>
            {% for token_datum in request.token_data %}
            <li data-label='token'>{{ token_datum.token }}</li>
            {% endfor %}
        </ul>

        {% for token_datum in request.token_data %}
        <input type="hidden" id="signature-{{ token_datum.token }}" name="signature-{{ token_datum.token }}" value="">
        <input type="hidden" id="token" name="token" value="{{ token_datum.token }}">
        <input type="hidden" id="token_time-{{ token_datum.token }}" name="token_time-{{ token_datum.token }}" value="{{ token_datum.token_time }}">
        {% endfor %}
        <input type="hidden" name="name" value="{{ request.name }}">
        <input type="hidden" name="description" value="{{ request.description }}">
        {% for experiment in request.experiments %}
        <input type="hidden" name="experiments" value="{{ experiment.id }}">
        {% endfor %}
        <p id="action-required-genecoop-plugin" class="space instruction">
            Please 'Sign' this request with your GeneCoop add-on.
        </p>
        <p id="action-done-genecoop-plugin" class="space instruction" style="display: none;visibility: hidden;">
            Signing successful. Click on 'Proceed' to continue.
        </p>
        <div class="form-buttons">
          <input id="submit" type="submit" value="Proceed" disabled>
        </div>
    </form>

</div>

{% endblock %}

Demonstrator/ResearchInterface/researcher_app/templates/researcher_app/vc.html
{% extends 'base_res.html' %}

{% block title %}Request{% endblock %}


{% block content %}

<div class="container">
    <h2>Request</h2>


    <ul class="responsive-table">
        <li class="table-header">
            <div class="col col-14">Name of Request</div>
            <div class="col col-24">Request Description</div>
            <!-- <div class="col col-3">User id</div> -->
            <div class="col col-34">Token</div>
            <div class="col col-44">Status</div>

        </li>
        <li class="table-row">
            <div class="col col-14" data-label="name">{{ request.name }}</div>
            <div class="col col-24" data-label="description">{{ request.description }}</div>
            <!-- <div class="col col-3" data-label="userid">{{ request.user_id }}</div> -->
            <div class="col col-34" data-label="token">{{ request.token }}</div>
            <div class="col col-44" data-label="status">{{ request.status }}</div>
        </li>
    </ul>
    
    <h2>Experiments</h2>
    <ul class="responsive-table">
        <li class="table-header">
            <div class="col col-15">Name of Experiment</div>
            <div class="col col-25">Experiment Description</div>
            <div class="col col-35">Consent</div>
            <div class="col col-45">Reply</div>
            <div class="col col-55">Action</div>
        </li>
        {% for experiment in request.experiments %}
        <li class="table-row">
            <div class="col col-15" data-label="Name">{{experiment.name }}</div>
            <div class="col col-25" data-label="Description">{{ experiment.description }}</div>
            <div class="col col-35" data-label="Consent">
                {% if experiment.chosen_option != -1 %}
                {{experiment.chosen_option_name}}
                {% else %}
                No reply
                {% endif %}
            </div>
            <div class="col col-45" data-label="Reply">{{ experiment.reply }}</div>
            <div class="col col-55" data-label="Submit">
                {% if request.status == "REPLIED" %}
                <form action="{% url 'researcher_app:perform_action' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" id="Token" name="Token" value={{request.token}}>
                    <input type="hidden" id="experimentId" name="experimentId" value={{experiment.id}}>
                    <input type="submit" value="Run Analysis">
                </form>
                {% else %}
                No experiment possible
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>


</div>

{% endblock %}